/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Onboarding */
        post: operations["complete_onboarding_api_v1_onboarding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/habits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Habits */
        get: operations["list_habits_api_v1_habits_get"];
        put?: never;
        /** Create Habit */
        post: operations["create_habit_api_v1_habits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/habits/{habit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Habit */
        delete: operations["delete_habit_api_v1_habits__habit_id__delete"];
        options?: never;
        head?: never;
        /** Update Habit */
        patch: operations["update_habit_api_v1_habits__habit_id__patch"];
        trace?: never;
    };
    "/api/v1/habits/{habit_id}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check In */
        post: operations["check_in_api_v1_habits__habit_id__checkin_post"];
        /** Undo Check In */
        delete: operations["undo_check_in_api_v1_habits__habit_id__checkin_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/habits/{habit_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Habit */
        post: operations["archive_habit_api_v1_habits__habit_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/habits/{habit_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Habit */
        post: operations["restore_habit_api_v1_habits__habit_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streaks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Streak */
        get: operations["get_streak_api_v1_streaks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streaks/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Use Freeze */
        post: operations["use_freeze_api_v1_streaks_freeze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/xp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Xp */
        get: operations["get_xp_api_v1_xp_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/level": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Level */
        get: operations["get_level_api_v1_level_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Heatmap */
        get: operations["get_heatmap_api_v1_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analytics */
        get: operations["get_analytics_api_v1_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roadmaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roadmaps */
        get: operations["list_roadmaps_api_v1_roadmaps_get"];
        put?: never;
        /** Create Roadmap */
        post: operations["create_roadmap_api_v1_roadmaps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roadmaps/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Roadmap */
        post: operations["import_roadmap_api_v1_roadmaps_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roadmaps/{roadmap_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roadmap */
        get: operations["get_roadmap_api_v1_roadmaps__roadmap_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roadmaps/{roadmap_id}/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle Topic */
        patch: operations["toggle_topic_api_v1_roadmaps__roadmap_id__topics__topic_id__patch"];
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals */
        get: operations["list_goals_api_v1_goals_get"];
        put?: never;
        /** Create Goal */
        post: operations["create_goal_api_v1_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal */
        get: operations["get_goal_api_v1_goals__goal_id__get"];
        put?: never;
        post?: never;
        /** Delete Goal */
        delete: operations["delete_goal_api_v1_goals__goal_id__delete"];
        options?: never;
        head?: never;
        /** Update Goal */
        patch: operations["update_goal_api_v1_goals__goal_id__patch"];
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/milestones/{milestone_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Milestone */
        patch: operations["update_milestone_api_v1_goals__goal_id__milestones__milestone_id__patch"];
        trace?: never;
    };
    "/api/v1/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Achievements */
        get: operations["list_achievements_api_v1_achievements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leaderboard */
        get: operations["leaderboard_api_v1_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Friends */
        get: operations["list_friends_api_v1_friends_get"];
        put?: never;
        /** Add Friend */
        post: operations["add_friend_api_v1_friends_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/friends/{friendship_id}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Respond Friend */
        post: operations["respond_friend_api_v1_friends__friendship_id__respond_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Challenges */
        get: operations["challenges_api_v1_challenges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_api_v1_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Read */
        post: operations["mark_all_read_api_v1_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_api_v1_settings_patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AchievementRead */
        AchievementRead: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string | null;
            /** Tier */
            tier: string;
            /** Target */
            target: number;
            /** Progress */
            progress: number;
            /** Unlocked */
            unlocked: boolean;
            /** Unlocked At */
            unlocked_at: string | null;
            /** Hidden */
            hidden: boolean;
        };
        /** AnalyticsRead */
        AnalyticsRead: {
            /** Period */
            period: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Total Checkins */
            total_checkins: number;
            /** Active Days */
            active_days: number;
            /** Perfect Days */
            perfect_days: number;
            /** Xp Earned */
            xp_earned: number;
            /** By Category */
            by_category: components["schemas"]["CategoryCount"][];
            /** Trend */
            trend: components["schemas"]["TrendPoint"][];
            /** Time Of Day */
            time_of_day: components["schemas"]["TimeOfDayBucket"][];
            /** Velocity */
            velocity: components["schemas"]["VelocityItem"][];
            records: components["schemas"]["AnalyticsRecords"];
        };
        /** AnalyticsRecords */
        AnalyticsRecords: {
            /** Longest Streak */
            longest_streak: number;
            /** Best Day Count */
            best_day_count: number;
            /** Total Checkins */
            total_checkins: number;
        };
        /** CategoryCount */
        CategoryCount: {
            /** Category */
            category: string;
            /** Count */
            count: number;
        };
        /** ChallengeRead */
        ChallengeRead: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Target */
            target: number;
            /** Progress */
            progress: number;
            /** Complete */
            complete: boolean;
        };
        /** CheckinRead */
        CheckinRead: {
            /** Id */
            id: number;
            /** Habit Id */
            habit_id: number;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CheckinResult */
        CheckinResult: {
            checkin: components["schemas"]["CheckinRead"];
            /** Xp Awarded */
            xp_awarded: number;
            /** Perfect Day */
            perfect_day: boolean;
            /** Current Streak */
            current_streak: number;
        };
        /**
         * EvolutionStage
         * @enum {string}
         */
        EvolutionStage: "Spark" | "Ember" | "Flame" | "Blaze" | "Inferno" | "Eternal";
        /** FreezeResult */
        FreezeResult: {
            /** Current Daily */
            current_daily: number;
            /** Freeze Balance */
            freeze_balance: number;
            /** Protected */
            protected: boolean;
            /** Message */
            message: string;
        };
        /** FriendRead */
        FriendRead: {
            /** Friendship Id */
            friendship_id: number;
            /** User Id */
            user_id: number;
            /** Display Name */
            display_name: string;
            /** Avatar Seed */
            avatar_seed: string | null;
            /** Level */
            level: number;
            /** Xp Total */
            xp_total: number;
            /** Status */
            status: string;
            /** Direction */
            direction: string;
        };
        /** FriendRequestCreate */
        FriendRequestCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** FriendRespond */
        FriendRespond: {
            /** Accept */
            accept: boolean;
        };
        /** FriendsList */
        FriendsList: {
            /** Friends */
            friends: components["schemas"]["FriendRead"][];
            /** Incoming Requests */
            incoming_requests: components["schemas"]["FriendRead"][];
            /** Outgoing Requests */
            outgoing_requests: components["schemas"]["FriendRead"][];
        };
        /** FriendshipRead */
        FriendshipRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Friend Id */
            friend_id: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** GoalCreate */
        GoalCreate: {
            /** Name */
            name: string;
            /** Icon */
            icon?: string | null;
            /** Color */
            color?: string | null;
            /** Deadline */
            deadline?: string | null;
            /** Started At */
            started_at?: string | null;
            /**
             * Milestones
             * @default []
             */
            milestones: components["schemas"]["MilestoneCreate"][];
            /**
             * Habit Ids
             * @default []
             */
            habit_ids: number[];
        };
        /** GoalRead */
        GoalRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Icon */
            icon: string | null;
            /** Color */
            color: string | null;
            /** Deadline */
            deadline: string | null;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["GoalStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Milestones
             * @default []
             */
            milestones: components["schemas"]["MilestoneRead"][];
            /**
             * Habit Ids
             * @default []
             */
            habit_ids: number[];
            /**
             * Done Milestones
             * @default 0
             */
            done_milestones: number;
            /**
             * Total Milestones
             * @default 0
             */
            total_milestones: number;
            /**
             * Progress Pct
             * @default 0
             */
            progress_pct: number;
        };
        /**
         * GoalStatus
         * @enum {string}
         */
        GoalStatus: "active" | "completed" | "archived";
        /** GoalUpdate */
        GoalUpdate: {
            /** Name */
            name?: string | null;
            /** Icon */
            icon?: string | null;
            /** Color */
            color?: string | null;
            /** Deadline */
            deadline?: string | null;
            status?: components["schemas"]["GoalStatus"] | null;
            /** Habit Ids */
            habit_ids?: number[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HabitCategory
         * @enum {string}
         */
        HabitCategory: "Fitness" | "Discipline" | "Learning" | "Focus" | "Mind" | "Health" | "Finance" | "Creativity";
        /** HabitCreate */
        HabitCreate: {
            /** Name */
            name: string;
            category: components["schemas"]["HabitCategory"];
            /** Icon */
            icon?: string | null;
            /**
             * Xp Value
             * @default 15
             */
            xp_value: number;
            /**
             * Schedule
             * @default daily
             */
            schedule: string;
            /** Linked Roadmap Id */
            linked_roadmap_id?: number | null;
        };
        /** HabitRead */
        HabitRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            category: components["schemas"]["HabitCategory"];
            /** Icon */
            icon: string | null;
            /** Xp Value */
            xp_value: number;
            /** Schedule */
            schedule: string;
            /** Archived */
            archived: boolean;
            /** Linked Roadmap Id */
            linked_roadmap_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Current Streak
             * @default 0
             */
            current_streak: number;
            /**
             * Checked In Today
             * @default false
             */
            checked_in_today: boolean;
        };
        /** HabitUpdate */
        HabitUpdate: {
            /** Name */
            name?: string | null;
            category?: components["schemas"]["HabitCategory"] | null;
            /** Icon */
            icon?: string | null;
            /** Xp Value */
            xp_value?: number | null;
            /** Schedule */
            schedule?: string | null;
            /** Linked Roadmap Id */
            linked_roadmap_id?: number | null;
        };
        /** HeatmapCell */
        HeatmapCell: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Count */
            count: number;
        };
        /** HeatmapRead */
        HeatmapRead: {
            /** Range */
            range: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Cells */
            cells: components["schemas"]["HeatmapCell"][];
        };
        /** LeaderboardEntryRead */
        LeaderboardEntryRead: {
            /** Rank */
            rank: number;
            /** User Id */
            user_id: number;
            /** Display Name */
            display_name: string;
            /** Avatar Seed */
            avatar_seed: string | null;
            /** Level */
            level: number;
            /** Xp */
            xp: number;
            /** Is Me */
            is_me: boolean;
        };
        /** LeaderboardRead */
        LeaderboardRead: {
            /** Scope */
            scope: string;
            /** Entries */
            entries: components["schemas"]["LeaderboardEntryRead"][];
            /** My Rank */
            my_rank: number | null;
        };
        /** LevelRead */
        LevelRead: {
            /** Level */
            level: number;
            /** Name */
            name: string;
            /** Xp Total */
            xp_total: number;
            /** Current Threshold */
            current_threshold: number;
            /** Next Threshold */
            next_threshold: number | null;
            /** Xp Into Level */
            xp_into_level: number;
            /** Xp To Next */
            xp_to_next: number | null;
            /** Progress Pct */
            progress_pct: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Avatar Seed */
            avatar_seed: string | null;
            /** Timezone */
            timezone: string;
            /** Identity Word */
            identity_word: string | null;
            /** Xp Total */
            xp_total: number;
            /** Onboarding Completed */
            onboarding_completed: boolean;
            /** Pact Accepted */
            pact_accepted: boolean;
            /** Focus Areas */
            focus_areas: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Level */
            level: number;
            /** Level Name */
            level_name: string;
            /** Xp To Next */
            xp_to_next: number | null;
        };
        /**
         * MentorTone
         * @enum {string}
         */
        MentorTone: "gentle" | "hard" | "relentless";
        /** MilestoneCreate */
        MilestoneCreate: {
            /** Name */
            name: string;
            /** Due Label */
            due_label?: string | null;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
        };
        /** MilestoneRead */
        MilestoneRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Due Label */
            due_label: string | null;
            /** Done */
            done: boolean;
            /** Completed At */
            completed_at: string | null;
            /** Order Index */
            order_index: number;
        };
        /** MilestoneUpdate */
        MilestoneUpdate: {
            /** Name */
            name?: string | null;
            /** Due Label */
            due_label?: string | null;
            /** Done */
            done?: boolean | null;
            /** Order Index */
            order_index?: number | null;
        };
        /** NotificationRead */
        NotificationRead: {
            /** Id */
            id: number;
            type: components["schemas"]["NotificationType"];
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Action Label */
            action_label: string | null;
            /** Action Url */
            action_url: string | null;
            /** Read At */
            read_at: string | null;
            /** Scheduled For */
            scheduled_for: string | null;
            /** Sent At */
            sent_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * NotificationType
         * @enum {string}
         */
        NotificationType: "streak_protection" | "milestone" | "accountability" | "reengagement" | "review" | "achievement" | "encouragement" | "social";
        /** OnboardingHabit */
        OnboardingHabit: {
            /** Name */
            name: string;
            category: components["schemas"]["HabitCategory"];
            /** Icon */
            icon?: string | null;
            /**
             * Xp Value
             * @default 20
             */
            xp_value: number;
        };
        /** OnboardingRequest */
        OnboardingRequest: {
            /** Focus Areas */
            focus_areas?: components["schemas"]["HabitCategory"][];
            /** Habits */
            habits?: components["schemas"]["OnboardingHabit"][];
            /**
             * Daily Target
             * @default 3
             */
            daily_target: number;
            /** Reminder Slot */
            reminder_slot?: string | null;
            /** @default hard */
            intensity: components["schemas"]["MentorTone"];
            /** Identity Word */
            identity_word?: string | null;
            /**
             * Pact Accepted
             * @default false
             */
            pact_accepted: boolean;
        };
        /** OnboardingResponse */
        OnboardingResponse: {
            user: components["schemas"]["MeResponse"];
            /** Habits Created */
            habits_created: number;
        };
        /** PhaseRead */
        PhaseRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Duration Label */
            duration_label: string | null;
            /** Order Index */
            order_index: number;
            /** Topics */
            topics: components["schemas"]["TopicRead"][];
            /**
             * Done Count
             * @default 0
             */
            done_count: number;
            /**
             * Total Count
             * @default 0
             */
            total_count: number;
            /**
             * Complete
             * @default false
             */
            complete: boolean;
        };
        /** ReadAllResult */
        ReadAllResult: {
            /** Marked Read */
            marked_read: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
            /**
             * Timezone
             * @default Europe/Berlin
             */
            timezone: string;
            /** Identity Word */
            identity_word?: string | null;
        };
        /** RoadmapCreate */
        RoadmapCreate: {
            /** Title */
            title: string;
            /** Icon */
            icon?: string | null;
            /** Color */
            color?: string | null;
            /**
             * Is Dsa Linked
             * @default false
             */
            is_dsa_linked: boolean;
        };
        /** RoadmapDetail */
        RoadmapDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Icon */
            icon: string | null;
            /** Color */
            color: string | null;
            /** Source */
            source: string;
            /** Is Dsa Linked */
            is_dsa_linked: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Total Topics
             * @default 0
             */
            total_topics: number;
            /**
             * Done Topics
             * @default 0
             */
            done_topics: number;
            /**
             * Progress Pct
             * @default 0
             */
            progress_pct: number;
            /**
             * Phases
             * @default []
             */
            phases: components["schemas"]["PhaseRead"][];
        };
        /** RoadmapImportRequest */
        RoadmapImportRequest: {
            /** Markdown */
            markdown: string;
            /** Icon */
            icon?: string | null;
            /** Color */
            color?: string | null;
            /**
             * Is Dsa Linked
             * @default false
             */
            is_dsa_linked: boolean;
        };
        /** RoadmapSummary */
        RoadmapSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Icon */
            icon: string | null;
            /** Color */
            color: string | null;
            /** Source */
            source: string;
            /** Is Dsa Linked */
            is_dsa_linked: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Total Topics
             * @default 0
             */
            total_topics: number;
            /**
             * Done Topics
             * @default 0
             */
            done_topics: number;
            /**
             * Progress Pct
             * @default 0
             */
            progress_pct: number;
        };
        /** SettingsRead */
        SettingsRead: {
            /** Theme */
            theme: string;
            /** Accent Color */
            accent_color: string;
            mentor_tone: components["schemas"]["MentorTone"];
            /** Sound Enabled */
            sound_enabled: boolean;
            /** Public On Leaderboards */
            public_on_leaderboards: boolean;
            /** Quiet Hours Start */
            quiet_hours_start: string | null;
            /** Quiet Hours End */
            quiet_hours_end: string | null;
            /** Daily Target */
            daily_target: number;
            /** Reminder Slot */
            reminder_slot: string | null;
            /** Notify Streak Protection */
            notify_streak_protection: boolean;
            /** Notify Milestone */
            notify_milestone: boolean;
            /** Notify Accountability */
            notify_accountability: boolean;
            /** Notify Reengagement */
            notify_reengagement: boolean;
            /** Notify Review */
            notify_review: boolean;
            /** Notify Achievement */
            notify_achievement: boolean;
            /** Notify Encouragement */
            notify_encouragement: boolean;
            /** Notify Social */
            notify_social: boolean;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Theme */
            theme?: string | null;
            /** Accent Color */
            accent_color?: string | null;
            mentor_tone?: components["schemas"]["MentorTone"] | null;
            /** Sound Enabled */
            sound_enabled?: boolean | null;
            /** Public On Leaderboards */
            public_on_leaderboards?: boolean | null;
            /** Quiet Hours Start */
            quiet_hours_start?: string | null;
            /** Quiet Hours End */
            quiet_hours_end?: string | null;
            /** Daily Target */
            daily_target?: number | null;
            /** Reminder Slot */
            reminder_slot?: string | null;
            /** Notify Streak Protection */
            notify_streak_protection?: boolean | null;
            /** Notify Milestone */
            notify_milestone?: boolean | null;
            /** Notify Accountability */
            notify_accountability?: boolean | null;
            /** Notify Reengagement */
            notify_reengagement?: boolean | null;
            /** Notify Review */
            notify_review?: boolean | null;
            /** Notify Achievement */
            notify_achievement?: boolean | null;
            /** Notify Encouragement */
            notify_encouragement?: boolean | null;
            /** Notify Social */
            notify_social?: boolean | null;
        };
        /** StreakRead */
        StreakRead: {
            /** Current Daily */
            current_daily: number;
            /** Longest */
            longest: number;
            /** Weekly Count */
            weekly_count: number;
            /** Monthly Count */
            monthly_count: number;
            /** Freeze Balance */
            freeze_balance: number;
            evolution_stage: components["schemas"]["EvolutionStage"];
        };
        /** TimeOfDayBucket */
        TimeOfDayBucket: {
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TopicRead */
        TopicRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Done */
            done: boolean;
            /** Completed At */
            completed_at: string | null;
            /** Order Index */
            order_index: number;
        };
        /** TopicToggleResult */
        TopicToggleResult: {
            topic: components["schemas"]["TopicRead"];
            /** Phase Complete */
            phase_complete: boolean;
            /** Roadmap Progress Pct */
            roadmap_progress_pct: number;
            /** Xp Awarded */
            xp_awarded: number;
            /** Dsa Habit Credited */
            dsa_habit_credited: boolean;
        };
        /** TopicUpdate */
        TopicUpdate: {
            /** Done */
            done: boolean;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Label */
            label: string;
            /** Value */
            value: number;
        };
        /** UpdateMeRequest */
        UpdateMeRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Identity Word */
            identity_word?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Avatar Seed */
            avatar_seed?: string | null;
        };
        /** UserPublic */
        UserPublic: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Avatar Seed */
            avatar_seed: string | null;
            /** Timezone */
            timezone: string;
            /** Identity Word */
            identity_word: string | null;
            /** Xp Total */
            xp_total: number;
            /** Onboarding Completed */
            onboarding_completed: boolean;
            /** Pact Accepted */
            pact_accepted: boolean;
            /** Focus Areas */
            focus_areas: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VelocityItem */
        VelocityItem: {
            /** Roadmap Id */
            roadmap_id: number;
            /** Title */
            title: string;
            /** Topics Done */
            topics_done: number;
        };
        /** XpEventRead */
        XpEventRead: {
            /** Amount */
            amount: number;
            /** Reason */
            reason: string;
            /** Ref Id */
            ref_id: number | null;
            /** Created At */
            created_at: unknown;
        };
        /** XpSummary */
        XpSummary: {
            /** Xp Total */
            xp_total: number;
            /** Level */
            level: number;
            /** Level Name */
            level_name: string;
            /** Recent Events */
            recent_events: components["schemas"]["XpEventRead"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    update_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_onboarding_api_v1_onboarding_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_habits_api_v1_habits_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_habit_api_v1_habits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HabitCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_habit_api_v1_habits__habit_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habit_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_habit_api_v1_habits__habit_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habit_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HabitUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_in_api_v1_habits__habit_id__checkin_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habit_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_check_in_api_v1_habits__habit_id__checkin_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habit_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_habit_api_v1_habits__habit_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habit_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_habit_api_v1_habits__habit_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habit_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_streak_api_v1_streaks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakRead"];
                };
            };
        };
    };
    use_freeze_api_v1_streaks_freeze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FreezeResult"];
                };
            };
        };
    };
    get_xp_api_v1_xp_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["XpSummary"];
                };
            };
        };
    };
    get_level_api_v1_level_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelRead"];
                };
            };
        };
    };
    get_heatmap_api_v1_heatmap_get: {
        parameters: {
            query?: {
                range?: "weeks" | "year";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_api_v1_analytics_get: {
        parameters: {
            query?: {
                period?: "week" | "month" | "year";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roadmaps_api_v1_roadmaps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapSummary"][];
                };
            };
        };
    };
    create_roadmap_api_v1_roadmaps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadmapCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_roadmap_api_v1_roadmaps_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadmapImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roadmap_api_v1_roadmaps__roadmap_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_topic_api_v1_roadmaps__roadmap_id__topics__topic_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: number;
                topic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicToggleResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_api_v1_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"][];
                };
            };
        };
    };
    create_goal_api_v1_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_goal_api_v1_goals__goal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_goal_api_v1_goals__goal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_goal_api_v1_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_milestone_api_v1_goals__goal_id__milestones__milestone_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: number;
                milestone_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MilestoneUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_achievements_api_v1_achievements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementRead"][];
                };
            };
        };
    };
    leaderboard_api_v1_leaderboard_get: {
        parameters: {
            query?: {
                scope?: "league" | "friends" | "global";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_friends_api_v1_friends_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendsList"];
                };
            };
        };
    };
    add_friend_api_v1_friends_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FriendRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendshipRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    respond_friend_api_v1_friends__friendship_id__respond_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendship_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FriendRespond"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendsList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    challenges_api_v1_challenges_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeRead"][];
                };
            };
        };
    };
    list_notifications_api_v1_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationRead"][];
                };
            };
        };
    };
    mark_read_api_v1_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_read_api_v1_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadAllResult"];
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
        };
    };
    update_settings_api_v1_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
